// app/layout.js
import localFont from "next/font/local";
import "./globals.css";
// import { ThemeProvider } from "./components/theme-provider";
// import Navbar from "./components/Navbar";
// import Topbar from "./components/Topbar";
// import Footer from "./components/Footer";
// import LoaderWrapper from "./components/LoaderWrapper"; // Import the new loader component
import { ThemeProvider } from "@/components/ui/theme-provider";
import Navbar from "@/components/ui/Navbar";
import Topbar from "@/components/ui/Topbar";
import Footer from "@/components/ui/Footer";
import LoaderWrapper from "@/components/ui/LoaderWrapper";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ahmed Homeopathy Clinic",
  description: "Generated by create next app",
  icons:{
    icon: '/logo.png',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/logo.png" sizes="any" />
      {/* Other meta tags can go here if needed */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <LoaderWrapper>
            <Topbar />
            <Navbar />
            {children}
            <Footer />
          </LoaderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
